apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe
  name: fe-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/fe-svc
spec:
  ports:
  - port: 80
    protocol: http
    targetPort: 80
  selector:
    app: fe
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}